[package]
name = "kiki_test"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
kiki = { path = "../kiki" }
walkdir = "2"

[dev-dependencies]
pretty_assertions = "1.3.0"
